osx_image: xcode8
language: objective-c

before_script:
    - cd Examples/PVOnboardKitExample
    - pod install
    
xcode_workspace: PVOnboardKitExample.xcworkspace
xcode_scheme: PVOnboardKitExample

after_script:
    - cd ../../

before_script:
    - cd Examples/PVOnboardKitSwiftExample
    - pod install

xcode_workspace: PVOnboardKitSwiftExample.xcworkspace
xcode_scheme: PVOnboardKitSwiftExample
