osx_image: xcode8.2
language: objective-c

before_script:
    - cd Examples/PVOnboardKitExample
    - pod install

xcode_workspace: PVOnboardKitExample.xcworkspace
xcode_scheme: PVOnboardKitExample
script: set -o pipefail
