osx_image: xcode8
language: objective-c

script: 
    - pod --project-directory=Examples/PVOnboardKitExample/ install
    - xcodebuild -workspace Examples/PVOnboardKitExample/PVOnboardKitExample.xcworkspace -sdk iphonesimulator -scheme PVOnboardKitExample build
    - pod --project-directory=Examples/PVOnboardKitSwiftExample/ install
    - xcodebuild -workspace Examples/PVOnboardKitSwiftExample/PVOnboardKitSwiftExample.xcworkspace -sdk iphonesimulator -scheme PVOnboardKitSwiftExample build
