osx_image: xcode8
language: objective-c

script: 
    - cd Examples/PVOnboardKitExample
    - pod install
    - xcodebuild -workspace PVOnboardKitExample.xcworkspace -scheme PVOnboardKitExample -destination platform='iOS Simulator',OS='10.0',name='iPhone 6s' build test
    - cd ../../
    - cd Examples/PVOnboardKitSwiftExample
    - pod install
    - xcodebuild -workspace PVOnboardKitSwiftExample.xcworkspace -scheme PVOnboardKitSwiftExample -destination platform='iOS Simulator',OS='10.0',name='iPhone 6s' build test
